### ISSUE TITLE
🚀 Release 2.4.3

### ISSUE THREAD

**Issue by clotairer** [202-ecommerce/stripe_official#121]
This issue tracks the status of the Stripe Official Module release 2.4.3 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 2.4.3
Estimated beta | March 2022
Estimated release | March 2022

## Current status

- [x] Specification
- [x] Feature development
  - [x] Fixbug: Capture amount issue with splitted orders (33104 & 33138) #128
  - [x] Fixbub: #129 by @s1239u85
  - [x] Fixbug: Wrong capture_method for sofort orders since v2.4.2 - payment rejected #122 
  - [x] Fixbug: Upon entering card details, error occurs for some customers #124 by @lnkmichaelknight #119 
- [x] Translation
- [x] Stabilization
- [x] Build (Beta) - March 21
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
