### ISSUE TITLE
🚀 Release 2.4.4

### ISSUE THREAD

**Issue by clotairer** [202-ecommerce/stripe_official#130]
This issue tracks the status of the Stripe Official Module release 2.4.4 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 2.4.4
Estimated beta | April 2022
Estimated release | April 2022

## Current status

- [x] Specification
- [x] Feature development
  - [x] Fixbug: Fix order confirmation page display (33970) #137 
  - [x] Fixbug: Fix date_add of stripe_event entries when status is CREATED (33969) #136 
  - [x] Fixbug: Fix unsupported ajaxDie method until Prestashop 1.6.0.12 (33955) #135
  - [x] Fixbug:  Translation string "payment via Stripe" #139 
  - [x] Fixbug: #142 
- [x] Translation
- [x] Stabilization
- [x] Build (Beta) - March 21
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
