### ISSUE TITLE
🚀 Release 2.4.5

### ISSUE THREAD

**Issue by clotairer** [202-ecommerce/stripe_official#141]
This issue tracks the status of the Stripe Official Module release 2.4.5 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 2.4.5
Estimated beta | August 2022
Estimated release | August 2022

## Current status

- [x] Specification
- [x] Feature development
  - [x] Fixbug: partial refund #55 (34683) #159
  - [x] Fixbug: form width and mastercard logo (35612) #148 Credit @lmeyer1 
  - [x] Fixbug: payment intent update error with an other payment method after failed of card payment (35025) #150
  - [x] Fixbug: capture error during payment with card  (35018) #151
  - [x] Fix bug #154 Credit @paul-jolimoi
  - [x] Fixbug: Card logos are not displayed on the checkout page (34209) #157
  - [x] Fixbug: Fix order id retrieve in orderSuccess controller #152 
  - [x] Fixbug: Fix webhook url validation in multishop context on PS 1.7.8.x #158 (34319)
  - [x] Improvement: Fix slower API calls in customer cards display (35213 #145 > Credit @gmauro99 & @testing3-apps ) #153
  - [x] improvment: Security htaccess (36112) #167
  - [x] improvment: github actions PHPCS and PHPStan (33608) #160
- [x] Translation
- [x] Stabilization
- [x] Build (Beta) - August 21
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [ ] Final release

**Comment by clotairer** [comment]
Closed by 
https://github.com/202-ecommerce/stripe_official/releases/tag/2.4.5
