### ISSUE TITLE
🚀 Release 2.4.6

### ISSUE THREAD

**Issue by clotairer** [202-ecommerce/stripe_official#168]
This issue tracks the status of the Stripe Official Module release 2.4.6 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 2.4.6
Estimated beta | September 2022
Estimated release | September 2022

## Current status

- [x] Specification
- [x] Feature development
  - [x] Fixbug: Regression on refund (by @nervusdm)  #175 #176
  - [x] Fixbug: Save cards (by @Afayadas) (36438) #177
  - [x] Fixbug: Fatal error in case of expired keys (by @clotairer) #180
  - [x] Refactor: Clean unnecessary code (by @clotairer) #179
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [x] Final release
