### ISSUE TITLE
🚀 Release 2.5.0

### ISSUE THREAD

**Issue by clotairer** [202-ecommerce/stripe_official#181]
This issue tracks the status of the Stripe Official Module release 2.5.0 for PrestaShop.

## Information

Q | A
-- | --
Type | Minor version
Milestone | 2.5.0
Estimated beta | November 2022
Estimated release | November 2022

## Current status

- [x] Specification
- [x] Feature development
  - [x] improvement: PrestaShop 8.0 compatibility (37392) #188
  - [x] Improvement: Add a custom hook to define stripe metadata (27526) #187
  - [x] Improvement: Add logo to card payment method in checkout page (36863) #190 
  - [x] Improvement: Explanation about local payment method usage (37133) #191 
  - [x] Fixbug: index error during webhook process (37457) #189
  - [x] Fixbug: no such payment intent error about module mode (37132) #192 
  - [x] Fixbug: configuration in all shop context (36274) #193 
- [x] Translation
- [x] Stabilization
- [x] Build (Beta)
- [x] QA validation (Beta)
- [x] Support team training // docs updates
- [x] Release (Beta)
- [ ] Final release
